In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("06_customer_data_dirty.csv")
df.head(10)

,customer_id,age,annual_income_inr,city,account_type,preferred_channel,signup_date,transactions_last_30d,avg_transaction_amount_inr
0,CUST0001,32,768000,Mumbai,Savings,Mobile,2024-08-21,9.0,6664.30
1,CUST0002,40,INR 770000,Mumbai,Current,Mobile,2019-06-24,21.0,2508.71
2,CUST0003,21,NaN,Bengaluru,Basic,Mobile,2018-08-27,16.0,7929.87
3,CUST0004,999,585500,Ahmedabad,Savings,Web,2022-12-14,16.0,3039.58
4,CUST0005,54,570000,Delhi,Premium,branch,2022-02-03,20.0,5056.26
5,CUST0006,34,306500,Delhi,Savings,Mobile,2020-02-18,14.0,4975.35
6,CUST0007,32 yrs,862000,Mumbai,Savings,Branch,17/02/2024,13.0,1332.89
7,CUST0008,58,591500,Delhi,Premium,Mobile,2019-02-12,19.0,1369.91
8,CUST0009,33,3258000,New Delhi,Premium,Web,2023-08-10,18.0,3732.06
9,CUST0010,43,833500,Mumbai,Savings,Mobile,2025-07-19,12.0,949.32

In [6]:
rows, columns = df.shape
print("Rows are:", rows)
print("Columns are:",columns)

Rows are: 460
Columns are: 9

In [10]:
print("Column Names:", list(df.columns))

Column Names: ['customer_id', 'age', 'annual_income_inr', 'city', 'account_type', 'preferred_channel', 'signup_date', 'transactions_last_30d', 'avg_transaction_amount_inr']

In [ ]:
# data type and non-null count
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460 entries, 0 to 459
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customer_id                 460 non-null    object
 1   age                         438 non-null    object
 2   annual_income_inr           429 non-null    object
 3   city                        444 non-null    object
 4   account_type                450 non-null    object
 5   preferred_channel           442 non-null    object
 6   signup_date                 448 non-null    object
 7   transactions_last_30d       439 non-null    float64
 8   avg_transaction_amount_inr  435 non-null    float64
dtypes: float64(2), object(7)
memory usage: 32.5+ KB
None

In [13]:
# All Statistical values for Dataframe
df.describe()

       transactions_last_30d  avg_transaction_amount_inr
count             439.000000                4.350000e+02
mean               19.897494                1.287812e+04
std                53.994681                8.863527e+04
min               -12.000000               -9.999000e+03
25%                11.000000                2.116905e+03
50%                15.000000                3.338330e+03
75%                20.000000                5.213915e+03
max               999.000000                1.250000e+06

In [16]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customer_id,460,440,CUST0167,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,438,63,21,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN
annual_income_inr,429,398,795000,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,444,40,Mumbai,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN
account_type,450,17,Savings,227,NaN,NaN,NaN,NaN,NaN,NaN,NaN
preferred_channel,442,15,Mobile,206,NaN,NaN,NaN,NaN,NaN,NaN,NaN
signup_date,448,408,2020-09-30,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
transactions_last_30d,439.0,NaN,NaN,NaN,19.897494,53.994681,-12.0,11.0,15.0,20.0,999.0
avg_transaction_amount_inr,435.0,NaN,NaN,NaN,12878.124138,88635.27145,-9999.0,2116.905,3338.33,5213.915,1250000.0

In [17]:
print(df.isnull().sum())

customer_id                    0
age                           22
annual_income_inr             31
city                          16
account_type                  10
preferred_channel             18
signup_date                   12
transactions_last_30d         21
avg_transaction_amount_inr    25
dtype: int64

In [18]:
print(df.isna().sum())

customer_id                    0
age                           22
annual_income_inr             31
city                          16
account_type                  10
preferred_channel             18
signup_date                   12
transactions_last_30d         21
avg_transaction_amount_inr    25
dtype: int64

In [19]:
print(df.duplicated().sum())

12

In [25]:
print(df["age"].duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
455     True
456     True
457     True
458     True
459     True
Name: age, Length: 460, dtype: bool